### ISSUE TITLE
Beyond Good & Evil HD BF Support.

### ISSUE THREAD

**Issue by Lilothestitch16** [panzi/bgebf#2]
Is it possible to add support for the .bf files from Beyond Good & Evil HD on the Xbox 360 and Playstation 3 Version? I tried to extract it and it gave me an error that said File Formats Check Failed.
![BF Error](https://user-images.githubusercontent.com/8963276/104501284-e38c5b00-55b5-11eb-92c8-c8d31c95c1b6.png)

**Comment by panzi** [comment]
Well, I don't have those versions of the game and even if I would have I wouldn't know how to get the data of console games. So no, its not possible to me. (And have no time and don't feel like doing it anyway.)

**Comment by Lilothestitch16** [comment]
I was gonna send you the bf file from the HD Version but I guess not.

**Comment by panzi** [comment]
That would be a copyright violation.

**Comment by Lilothestitch16** [comment]
Do you know anyone that can take request to make game extracting and viewing tools for games by any chance?

**Comment by panzi** [comment]
Nope, sorry. I only do this for fun for the games I actually own on PC. The only other people I know of that are interested in these things are the ones that write bug reports here. 😄

**Comment by sabatale** [comment]
@Escope12 You're probably looking for [quickBMS](http://aluigi.altervista.org/quickbms.htm).
